apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: addons
spec:
  amiFamily: AL2
  role: ${nodeIamRoleName}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${clusterName}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${clusterName}
  tags:
    karpenter.sh/discovery: ${clusterName}